// TODO: convert this to a database table.

/** Retreat/Program Categories */
export const ENTITY_CATEGORIES = [
  "Adventure",
  "Ayurveda",
  "Couples",
  "Creative & Art",
  "Detox",
  "Emotional Wellness",
  "Family & Group",
  "Fitness",
  "Holistic",
  "Hydrotherapy",
  "Leadership",
  "Longevity",
  "Medical",
  "Meditation",
  "Mindfulness",
  "Motherhood",
  "Nature",
  "Nutrition",
  "Optimal Weight",
  "Outdoor",
  "Personal Growth",
  "Plant Medicine",
  "Relaxation",
  "Romantic",
  "Shamanic",
  "Sleep & Restorative",
  "Sound Healing",
  "Spa",
  "Sustainable",
  "Therapeutic Fasting",
  "Traditional Healing",
  "Women’s Health",
  "Men’s Health",
  "Yoga",
];
